xporta -T stable-set-10-0.poi
xporta -T stable-set-10-1.poi
xporta -T stable-set-10-2.poi
xporta -T stable-set-10-3.poi
xporta -T stable-set-10-4.poi
xporta -T stable-set-10-5.poi
xporta -T stable-set-10-6.poi
xporta -T stable-set-10-7.poi
xporta -T stable-set-10-8.poi
xporta -T stable-set-10-9.poi
xporta -T stable-set-20-0.poi
xporta -T stable-set-20-1.poi
xporta -T stable-set-20-2.poi
xporta -T stable-set-20-3.poi
xporta -T stable-set-20-4.poi
xporta -T stable-set-20-5.poi
xporta -T stable-set-20-6.poi
xporta -T stable-set-20-7.poi
xporta -T stable-set-20-8.poi
xporta -T stable-set-20-9.poi
xporta -T stable-set-30-0.poi
xporta -T stable-set-30-1.poi
xporta -T stable-set-30-2.poi
xporta -T stable-set-30-3.poi
xporta -T stable-set-30-4.poi
xporta -T stable-set-30-5.poi
xporta -T stable-set-30-6.poi
xporta -T stable-set-30-7.poi
xporta -T stable-set-30-8.poi
xporta -T stable-set-30-9.poi
xporta -T stable-set-40-0.poi
xporta -T stable-set-40-1.poi
xporta -T stable-set-40-2.poi
xporta -T stable-set-40-3.poi
xporta -T stable-set-40-4.poi
xporta -T stable-set-40-5.poi
xporta -T stable-set-40-6.poi
xporta -T stable-set-40-7.poi
xporta -T stable-set-40-8.poi
xporta -T stable-set-40-9.poi
xporta -T stable-set-50-0.poi
xporta -T stable-set-50-1.poi
xporta -T stable-set-50-2.poi
xporta -T stable-set-50-3.poi
xporta -T stable-set-50-4.poi
xporta -T stable-set-50-5.poi
xporta -T stable-set-50-6.poi
xporta -T stable-set-50-7.poi
xporta -T stable-set-50-8.poi
xporta -T stable-set-50-9.poi
xporta -T stable-set-60-0.poi
xporta -T stable-set-60-1.poi
xporta -T stable-set-60-2.poi
xporta -T stable-set-60-3.poi
xporta -T stable-set-60-4.poi
xporta -T stable-set-60-5.poi
xporta -T stable-set-60-6.poi
xporta -T stable-set-60-7.poi
xporta -T stable-set-60-8.poi
xporta -T stable-set-60-9.poi
xporta -T stable-set-70-0.poi
xporta -T stable-set-70-1.poi
xporta -T stable-set-70-2.poi
xporta -T stable-set-70-3.poi
xporta -T stable-set-70-4.poi
xporta -T stable-set-70-5.poi
xporta -T stable-set-70-6.poi
xporta -T stable-set-70-7.poi
xporta -T stable-set-70-8.poi
xporta -T stable-set-70-9.poi
xporta -T stable-set-80-0.poi
xporta -T stable-set-80-1.poi
xporta -T stable-set-80-2.poi
xporta -T stable-set-80-3.poi
xporta -T stable-set-80-4.poi
xporta -T stable-set-80-5.poi
xporta -T stable-set-80-6.poi
xporta -T stable-set-80-7.poi
xporta -T stable-set-80-8.poi
xporta -T stable-set-80-9.poi
xporta -T stable-set-90-0.poi
xporta -T stable-set-90-1.poi
xporta -T stable-set-90-2.poi
xporta -T stable-set-90-3.poi
xporta -T stable-set-90-4.poi
xporta -T stable-set-90-5.poi
xporta -T stable-set-90-6.poi
xporta -T stable-set-90-7.poi
xporta -T stable-set-90-8.poi
xporta -T stable-set-90-9.poi
